### ISSUE TITLE
有关BGABanner-Android这个框架的问题

### ISSUE THREAD

**Issue by Troll4it** [ywanhzy/MenuManage-Imitate-Alipay#2]
您好，冒昧的在这里提无关次此框架的问题。。我在BGABanner-Android这个框架中看到你提了一个有关动态改变banner高度的问题，后来说自己解决了，求教你是怎么解决的，能够提供相关的代码，谢谢

**Comment by ywanhzy** [comment]
@Troll4it 你要改BGABanner-Android 项目中的BGABanner文件  重写onMeasure方法

 private float ratio = 2f;//设置宽高比 2:1
public void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        //1.从widthMeasureSpec中反向获取父VIew计算好的size
        int width = MeasureSpec.getSize(widthMeasureSpec);
        //2.根据宽高比和width，计算出对应的height
        if(ratio!=0){
            float height = width/ratio;
            //3.重新组建heightMeasureSpec，传递给super.onMeasure
            heightMeasureSpec = MeasureSpec.makeMeasureSpec((int) height,MeasureSpec.EXACTLY);
        }
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
    }
这样就Ok了

**Comment by Troll4it** [comment]
意思就是重写onMeasure方法，又要在外层重新设置其需要的宽高

**Comment by xiaoxiyang09** [comment]
请教下，可拖拽排序的部分，能否像新版支付宝那样，当下面的列表向上滑动时，顶部可拖拽排序的部分是固定不变的？作者能否实现下？如果自己单独改，主要改哪些部分？谢谢
